### ISSUE TITLE
Комментарий от ментора: ДЗ №3

### ISSUE THREAD

**Issue by Petergod** [VitalikOstapenko/VitalikOstapenko.github.io#2]
- h1 для картинки не нужно , нужно див, h1 только для текста 
- копирайт нельзя брать в список, нужно в отдельный блок и задать флоат http://joxi.ru/ZrJpEb6SVPOx2j
- ширину для header .topmenu можно было не задавать) 
- Вместо position: relative; overflow: hidden; лучше использовать clearfix.  
- стили текста(сам шрифт и размер) topmenu left_menu  и так далее, можно было не задавать , Вы указали в начале документа.

**Comment by VitalikOstapenko** [comment]
* √ h1 - **убрал**, Олег Змиюк, на бесплатном вебинаре показывал так делать для SEO
* √ копирайт - **убрал** в div с float:right
* √ ширину для header .tomenu - **убрал**
* √ вставил везде **clearfix** класс для всех родительских контейнеров с флоатами - .topmenu, .container, foot_menu
* √ font-family - **убрал** везде кроме body, а font-size в четырех местах и он разный - поэтому оставил

**Comment by Petergod** [comment]
**Зачет**
